[package]
name = "runtime-arg-builder"
version = "0.1.0"
edition = "2018"

[dependencies]
casper-types = "1.3.3"
hex = { version = "0.4.3", features = ["serde"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
